<?php

namespace eStore\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
        
class CategoryRepository extends NestedTreeRepository
{
    
    /**
     * @todoChecked >Find more eficiant and the right way to get all products<
     * 
     */
    public function getAllProductsByCategory($category) 
    {
        $left  = $category->getLft();
        $right = $category->getRgt();
        
        $query = $this->_em->createQuery("SELECT p 
                                          FROM eStore\ShopBundle\Entity\Product p
                                          JOIN p.categories c
                                          WHERE c.lft BETWEEN $left AND $right");
        return $query->getResult();
    }
    
    
    public function getArrWithoutRoot() 
    {
        $categories = $this->childrenQuery()->getArrayResult();
        
        unset($categories[0]);
        
        return $categories;        
    }
    
}