<?php

namespace eStore\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
        
class ColourRepository extends EntityRepository
{    
}