<?php
namespace eStore\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getPopularProducts()
    {
        $qb = $this->createQueryBuilder('p')
                   ->select('p')
                   ->addOrderBy('p.id', 'ASC');
    
        return $qb->getQuery()
                  ->getResult();
    }
}