<?php
namespace eStore\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use eStore\ShopBundle\Entity\Product;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     *
     * @todo You could use DISTINCT clause
     */
    public function getPopularProducts()
    {
        $query = $this->_em
                      ->createQuery("SELECT p, c, cp
                                     FROM eStore\ShopBundle\Entity\Product p
                                     JOIN p.categories c
                                     LEFT JOIN c.parent cp
                                     ORDER BY p.id DESC
                                   ");
        return $query;
    }
    
    /**
     *
     * @return type 
     */
    public function getProducts()
    {
        $query = $this->_em
                      ->createQuery("SELECT p
                                     FROM eStore\ShopBundle\Entity\Product p
                                     ORDER BY p.id DESC
                                   ");
        return $query;
    }
}