<?php

namespace eStore\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
        
class UserRepository extends EntityRepository
{
    public function getUsersByRoles($role)
    {
        $query = $this->_em->createQuery("
                                      SELECT u 
                                      FROM eStore\ShopBundle\Entity\User u
                                      WHERE u.roles LIKE :role
                                      ORDER BY u.roles");
        $query->setParameters(array(
            'role' => '%' . $role . '%'
        ));

        return $query->getResult();
    }
}