eStoreShopBundleAdmin_index:
    pattern:  /
    defaults: { _controller: eStoreShopBundle:Admin:index }
    
eStoreShopBundleAdmin_product_list:
    pattern:  /products/list/{page}
    defaults: { _controller: eStoreShopBundle:Product:list, page: 1 }
    requirements:
        _method:  GET
        page: \d+
        
eStoreShopBundleAdmin_product_new:
    pattern:  /products/new
    defaults: { _controller: eStoreShopBundle:Product:new }

eStoreShopBundleAdmin_product_create:
    pattern:  /products/create
    defaults: { _controller: eStoreShopBundle:Product:create }
    requirements:
        _method:  POST
        
eStoreShopBundleAdmin_product_edit:
    pattern:  /products/edit/{id}
    defaults: { _controller: eStoreShopBundle:Product:edit }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleAdmin_product_update:
    pattern:  /products/update/{id}
    defaults: { _controller: eStoreShopBundle:Product:update }
    requirements:
        _method:  POST
        id: \d+

eStoreShopBundleAdmin_product_delete:
    pattern:  /products/delete/{id}
    defaults: { _controller: eStoreShopBundle:Product:delete }
    requirements:
        _method:  GET
        id: \d+

eStoreShopBundleAdmin_category_list:
    pattern:  /categories/list
    defaults: { _controller: eStoreShopBundle:Category:list }

eStoreShopBundleAdmin_category_new:
    pattern:  /categories/new
    defaults: { _controller: eStoreShopBundle:Category:new }
    requirements:
        _method:  GET
        
eStoreShopBundleAdmin_category_create:
    pattern:  /categories/create
    defaults: { _controller: eStoreShopBundle:Category:create }
    requirements:
        _method:  POST
 
eStoreShopBundleAdmin_category_movedown:
    pattern:  /categories/move/down/{id}
    defaults: { _controller: eStoreShopBundle:Category:moveDown }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleAdmin_category_moveup:
    pattern:  /categories/move/up/{id}
    defaults: { _controller: eStoreShopBundle:Category:moveUp }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleAdmin_category_delete:
    pattern:  /categories/delete/{id}
    defaults: { _controller: eStoreShopBundle:Category:delete }
    requirements:
        _method:  GET
        id: \d+

eStoreShopBundleAdmin_category_edit:
    pattern:  /categories/edit/{id}
    defaults: { _controller: eStoreShopBundle:Category:edit }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleAdmin_category_update:
    pattern:  /categories/update/{id}
    defaults: { _controller: eStoreShopBundle:Category:update }
    requirements:
        _method:  POST
        id: \d+