eStoreShopBundle_home:
    pattern:  /
    defaults: { _controller: eStoreShopBundle:Store:index }
    
eStoreShopBundle_about:
    pattern:  /about
    defaults: { _controller: eStoreShopBundle:Store:about }
    
eStoreShopBundle_contact:
    pattern:  /contact
    defaults: { _controller: eStoreShopBundle:Store:contact }
    requirements:
        _method:  GET|POST

eStoreShopBundle_product:
    pattern:  /{id}/{slug}
    defaults: { _controller: eStoreShopBundle:Product:index }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundle_category:
    pattern:  /category/{id}/{slug}
    defaults: { _controller: eStoreShopBundle:Category:index }
    requirements:
        _method:  GET
        id: \d+

eStoreShopBundle_cart:
    pattern:  /cart
    defaults: { _controller: eStoreShopBundle:Cart:viewCart }
    
eStoreShopBundle_addToCart:
    pattern:  /cart/add/{id}
    defaults: { _controller: eStoreShopBundle:Cart:addToCart }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundle_removeFromCart:
    pattern:  /cart/remove/{id}
    defaults: { _controller: eStoreShopBundle:Cart:removeFromCart }
    requirements:
        _method:  GET
        id: \d+  
        
eStoreShopBundle_emptyCart:
    pattern:  /cart/empty
    defaults: { _controller: eStoreShopBundle:Cart:emptyCart }
    requirements:
        _method:  GET
        
eStoreShopBundleApi:
    resource: "@eStoreShopBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    
eStoreShopBundleAdmin:
    resource: "@eStoreShopBundle/Resources/config/routing_admin.yml"
    prefix:   /admin
    type: rest