eStoreShopBundle_home:
    pattern:  /
    defaults: { _controller: eStoreShopBundle:Store:index }
    
eStoreShopBundle_about:
    pattern:  /about
    defaults: { _controller: eStoreShopBundle:Store:about }
    
eStoreShopBundle_contact:
    pattern:  /contact
    defaults: { _controller: eStoreShopBundle:Store:contact }

eStoreShopBundle_product:
    pattern:  /{id}/{slug}
    defaults: { _controller: eStoreShopBundle:Product:index }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundle_categories:
    pattern:  /categories/{id}/{slug}
    defaults: { _controller: eStoreShopBundle:Category:index }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundle_api_products:
    pattern:  /api/products/{page}
    defaults: { _controller: eStoreShopBundle:Api:getProducts, page: 1 }
    requirements:
        _method:  GET      