eStoreShopBundleAdmin_index:
    pattern:  /
    defaults: { _controller: eStoreShopBundle:Admin:index }
    
eStoreShopBundleAdmin_product_list:
    pattern:  /products/list
    defaults: { _controller: eStoreShopBundle:Product:list }
    
eStoreShopBundleAdmin_category_list:
    pattern:  /categories/list
    defaults: { _controller: eStoreShopBundle:Category:list }
    
eStoreShopBundleAdmin_category_movedown:
    pattern:  /categories/move/down/{id}
    defaults: { _controller: eStoreShopBundle:Category:moveDown }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleAdmin_category_moveup:
    pattern:  /categories/move/up/{id}
    defaults: { _controller: eStoreShopBundle:Category:moveUp }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleAdmin_category_delete:
    pattern:  /categories/delete/{id}
    defaults: { _controller: eStoreShopBundle:Category:delete }
    requirements:
        _method:  GET
        id: \d+

eStoreShopBundleAdmin_category_edit:
    pattern:  /categories/edit/{id}
    defaults: { _controller: eStoreShopBundle:Category:edit }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleAdmin_category_update:
    pattern:  /categories/update/{id}
    defaults: { _controller: eStoreShopBundle:Category:update }
    requirements:
        _method:  POST
        id: \d+