eStoreShopBundle_home:
    pattern:  /
    defaults: { _controller: eStoreShopBundle:Store:index }
    
eStoreShopBundle_about:
    pattern:  /about
    defaults: { _controller: eStoreShopBundle:Store:about }
    
eStoreShopBundle_contact:
    pattern:  /contact
    defaults: { _controller: eStoreShopBundle:Store:contact }

eStoreShopBundle_product:
    pattern:  /{id}/{slug}
    defaults: { _controller: eStoreShopBundle:Product:index }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundle_category:
    pattern:  /category/{id}/{slug}
    defaults: { _controller: eStoreShopBundle:Category:index }
    requirements:
        _method:  GET
        id: \d+
        
eStoreShopBundleApi:
    resource: "@eStoreShopBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest