parameters:
#    e_store_shop.example.class: eStore\ShopBundle\Example

services:
#    e_store_shop.example:
#        class: %e_store_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]