parameters:
#    e_store_shop.example.class: eStore\ShopBundle\Example

services:
#    e_store_shop.example:
#        class: %e_store_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


services:
    estore_shop.twig.extension:
        class: eStore\ShopBundle\Twig\Extension\RepeatExtension
        tags:
            - { name: twig.extension }
            
    estore_shop.cart.controller:
        class:  "eStore\ShopBundle\Controller\CartController"
        shared: true
        calls:
            - [ setContainer, ["@service_container"] ]
            
    user.registration.form.type:
        class: eStore\ShopBundle\Form\UserRegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_registration }
            
    user.form.handler.registration:
        class: eStore\ShopBundle\Form\Handler\UserRegistrationHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false
        
        
    admin.registration.form.type:
        class: eStore\ShopBundle\Form\Admin\AdminRegistrationType
        arguments: [%fos_user.model.user.class%, %security.role_hierarchy.roles%]
        tags:
            - { name: form.type, alias: admin_registration }