<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111223202646 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE category ADD slug VARCHAR(128) NOT NULL, CHANGE description description LONGTEXT NOT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX UNIQ_64C19C1989D9B62 ON category");
        $this->addSql("ALTER TABLE category DROP slug, CHANGE description description LONGTEXT DEFAULT NULL");
    }
}
