<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130209040136 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE estore_order ADD product_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE estore_order ADD CONSTRAINT FK_29B4A91A4584665A FOREIGN KEY (product_id) REFERENCES product(id)");
        $this->addSql("ALTER TABLE estore_order ADD CONSTRAINT FK_29B4A91A9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer(id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_29B4A91A4584665A ON estore_order (product_id)");
        $this->addSql("CREATE INDEX IDX_29B4A91A9395C3F3 ON estore_order (customer_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE estore_order DROP FOREIGN KEY FK_29B4A91A4584665A");
        $this->addSql("ALTER TABLE estore_order DROP FOREIGN KEY FK_29B4A91A9395C3F3");
        $this->addSql("DROP INDEX UNIQ_29B4A91A4584665A ON estore_order");
        $this->addSql("DROP INDEX IDX_29B4A91A9395C3F3 ON estore_order");
        $this->addSql("ALTER TABLE estore_order DROP product_id");
    }
}
