<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120114121753 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE product ADD code VARCHAR(255) NOT NULL, ADD quantity INT NOT NULL, ADD active TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE category_product DROP FOREIGN KEY FK_149244D34584665A");
        $this->addSql("ALTER TABLE category_product DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE category_product ADD CONSTRAINT FK_149244D34584665A FOREIGN KEY (product_id) REFERENCES product(id)");
        $this->addSql("ALTER TABLE category_product ADD PRIMARY KEY (product_id, category_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE category_product DROP FOREIGN KEY FK_149244D34584665A");
        $this->addSql("ALTER TABLE category_product DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE category_product ADD CONSTRAINT FK_149244D34584665A FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE category_product ADD PRIMARY KEY (category_id, product_id)");
        $this->addSql("ALTER TABLE product DROP code, DROP quantity, DROP active");
    }
}
