<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120114133214 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE product ADD quantity INT NOT NULL, ADD active TINYINT(1) NOT NULL, CHANGE image_name image_name VARCHAR(255) NOT NULL, CHANGE pcode code VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE product DROP quantity, DROP active, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE code pcode VARCHAR(255) DEFAULT NULL");
    }
}
