<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120107142358 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX UNIQ_D34A04AD989D9B62 ON product");
        $this->addSql("ALTER TABLE product DROP slug");
        $this->addSql("DROP INDEX UNIQ_64C19C1989D9B62 ON category");
        $this->addSql("ALTER TABLE category DROP slug");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE category ADD slug VARCHAR(128) NOT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)");
        $this->addSql("ALTER TABLE product ADD slug VARCHAR(128) NOT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_D34A04AD989D9B62 ON product (slug)");
    }
}
