<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120204161849 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE garment_colour DROP FOREIGN KEY FK_AD2DCCFA9CDB257C");
        $this->addSql("ALTER TABLE garment_colour ADD CONSTRAINT FK_AD2DCCFA9CDB257C FOREIGN KEY (garment_id) REFERENCES garment(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE garment_colour DROP FOREIGN KEY FK_AD2DCCFA9CDB257C");
        $this->addSql("ALTER TABLE garment_colour ADD CONSTRAINT FK_AD2DCCFA9CDB257C FOREIGN KEY (garment_id) REFERENCES garment(id)");
    }
}
