<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120115132813 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE product_attribute DROP FOREIGN KEY FK_94DA5976B6E62EFA");
        $this->addSql("ALTER TABLE attribute DROP FOREIGN KEY FK_FA7AEFFBFE54D947");
        $this->addSql("ALTER TABLE product_attribute DROP FOREIGN KEY FK_94DA5976FE54D947");
        $this->addSql("DROP TABLE attribute");
        $this->addSql("DROP TABLE attribute_group");
        $this->addSql("DROP TABLE product_attribute");
        $this->addSql("ALTER TABLE product ADD size VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE attribute (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_FA7AEFFBFE54D947 (group_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE attribute_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE product_attribute (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, product_id INT DEFAULT NULL, attribute_id INT DEFAULT NULL, INDEX IDX_94DA59764584665A (product_id), INDEX IDX_94DA5976B6E62EFA (attribute_id), INDEX IDX_94DA5976FE54D947 (group_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFBFE54D947 FOREIGN KEY (group_id) REFERENCES attribute_group(id)");
        $this->addSql("ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA5976FE54D947 FOREIGN KEY (group_id) REFERENCES attribute_group(id)");
        $this->addSql("ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA59764584665A FOREIGN KEY (product_id) REFERENCES product(id)");
        $this->addSql("ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA5976B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute(id)");
        $this->addSql("ALTER TABLE product DROP size");
    }
}
