<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120116201923 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE brand (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE product ADD brand_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE product ADD CONSTRAINT FK_D34A04AD44F5D008 FOREIGN KEY (brand_id) REFERENCES brand(id)");
        $this->addSql("CREATE INDEX IDX_D34A04AD44F5D008 ON product (brand_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD44F5D008");
        $this->addSql("DROP TABLE brand");
        $this->addSql("ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD44F5D008");
        $this->addSql("DROP INDEX IDX_D34A04AD44F5D008 ON product");
        $this->addSql("ALTER TABLE product DROP brand_id");
    }
}
